# Generated by Django 5.1.4 on 2026-02-27 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MandiPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("commodity", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("market", models.CharField(max_length=100)),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("modal_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("arrival_date", models.DateField()),
            ],
            options={
                "ordering": ["-arrival_date", "commodity"],
            },
        ),
    ]
