# Generated by Django 5.1.4 on 2026-02-27 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("ai_diagnosis", models.TextField(blank=True, null=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("scan_date", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_scans",
                        to="farmers.farmer",
                    ),
                ),
            ],
            options={
                "ordering": ["-scan_date"],
            },
        ),
    ]
